#include <world.hpp>


World::World(glm::vec3& cameraPos) : cameraPos(cameraPos) {
    player = std::make_unique<Player>(cameraPos);


    this->makeTestingMap(4); // creates a 3x3x3 of chunks centered around the origin, each chunk is 16x16x16 blocks --- IGNORE ---
    meshWorkerThreadPool.addTask(meshWorker, std::ref(*this), glm::ivec3(0, 2, -4)); // add a task to the thread pool to generate the mesh for the chunks in the chunk generation queue, this will run on another thread, so that it doesn't block the main thread, and also to allow multiple chunks to be generated at the same time
};



void World::update() {
    player->update();
    // update the chunk generation queue based on the player's position, this will add chunks around the player to the chunk generation queue, so that they can be generated by the mesh worker thread
    //this->updateChunkGenerationQueue();
    

    // render and add the meshes from the meshqueue
    {
        std::unique_lock<std::mutex> lock(meshQueueMutex);
        
        while(!meshUploadQueue.empty()) {
            printf("Processing mesh upload queue, %zu meshes to upload\n", meshUploadQueue.size());
            ChunkMesh data = std::move(meshUploadQueue.front());
            meshUploadQueue.pop();

            lock.unlock(); // unlock while processing the mesh to allow other threads to push meshes to the queue

            RenderBuffer renderBuffer;
            renderBuffer.uploadChunkMesh(data);

            // adding the render buffer to the map of render buffers, so that it can be drawn when needed, 
            // also to prevent it from being deleted when the mesh worker thread finishes
            renderBuffers.emplace(std::make_tuple(data.x, data.y, data.z), std::make_unique<RenderBuffer>(std::move(renderBuffer)));

            lock.lock(); // lock again to check the queue condition
        }
    }

    // for now, draw all the chunks in the world
    this->drawChunks();
}


void World::makeTestingMap(int size) {
    for (int x = -size; x <= size; x++) {
        for (int y = -size; y <= size; y++) {
            for (int z = -size; z <= size; z++) {
                std::unique_ptr<Chunk> chunk = std::make_unique<Chunk>(x, y, z);
                //chunk->createRandomChunk();
                world.emplace(std::make_tuple(x, y, z), std::move(chunk));
            }
        }
    }

}


void World::drawChunks() const {
    for (const auto& [location, data] : renderBuffers) {
        data->draw();
    }
}


void World::updateChunkGenerationQueue() {
    // lock the chunk generation queue mutex to provent data from reading at the same time
    std::lock_guard<std::mutex> lock(chunkGenerationQueueMutex);


    // get player chunk coordinates
    glm::ivec3 playerChunkCoords = player->getChunkCoords();


    // TODO: make it so that it generates the chunk in the corner later, for now keep as is
    // ----------
    // THIS FUNCTION MIGHT BE TERRIBLY SLOW, MAKE SURE THAT IT MIGHT NOT BE
    // add chunks around the player to the chunk generation queue, this is used to determine which chunks need to be generated based on the player's position
    for (int x = -RENDER_DISTANCE + playerChunkCoords.x; x <= RENDER_DISTANCE + playerChunkCoords.x; x++) {
        for (int y = -RENDER_DISTANCE + playerChunkCoords.y; y <= RENDER_DISTANCE + playerChunkCoords.y; y++) {
            for (int z = -RENDER_DISTANCE + playerChunkCoords.z; z <= RENDER_DISTANCE + playerChunkCoords.z; z++) {
                std::tuple<int, int, int> chunkCoords = std::make_tuple(x, y, z);
                if (world.find(chunkCoords) == world.end() 
                    && std::find(chunkGenerationQueue.begin(), chunkGenerationQueue.end(), chunkCoords) == chunkGenerationQueue.end()) {
                    
                    chunkGenerationQueue.push_front(chunkCoords);
                }
            }
        }
    }
}