#include <world.hpp>


World::World(glm::vec3& cameraPos, Shader* shader) : cameraPos(cameraPos), shader(shader) {
    player = std::make_unique<Player>(cameraPos);

    //shader = std::make_unique<Shader>("../shaders/shader.vs", "../shaders/shader.fs");
    shader->use();


    this->makeTestingMap(16); // creates a 3x3x3 of chunks centered around the origin, each chunk is 16x16x16 blocks --- IGNORE ---
    for (const auto& [location, data] : world) {
        meshWorkerThreadPool.addTask(meshWorker, std::ref(*this), tupleToVec3i(location)); // add a task to the thread pool to generate the mesh for the chunks in the chunk generation queue, this will run on another thread, so that it doesn't block the main thread, and also to allow multiple chunks to be generated at the same time
    }
    //meshWorkerThreadPool.addTask(meshWorker, std::ref(*this), glm::ivec3(0, 0, 0)); // add a task to the thread pool to generate the mesh for the chunks in the chunk generation queue, this will run on another thread, so that it doesn't block the main thread, and also to allow multiple chunks to be generated at the same time
};



void World::update() {
    player->update();
    // update the chunk generation queue based on the player's position, this will add chunks around the player to the chunk generation queue, so that they can be generated by the mesh worker thread
    //this->updateChunkGenerationQueue();
    

    // Set view and projection and position
    shader->setMat4("view", player->GetViewMatrix());
    shader->setMat4("projection", player->GetProjectionMatrix());

    glm::mat4 model = glm::mat4(1.0f);
    shader->setMat4("model", model);


    // render and add the meshes from the meshqueue
    {
        std::unique_lock<std::mutex> lock(meshQueueMutex);
        
        while(!meshUploadQueue.empty()) {
            ChunkMesh data = std::move(meshUploadQueue.front());
            meshUploadQueue.pop();

        

            lock.unlock(); // unlock while processing the mesh to allow other threads to push meshes to the queue
            
            std::unique_ptr<RenderBuffer> renderBuffer = std::make_unique<RenderBuffer>();

            // adding the render buffer to the map of render buffers, so that it can be drawn when needed, 
            // also to prevent it from being deleted when the mesh worker thread finishes
            renderBuffers.emplace(std::make_tuple(data.x, data.y, data.z), std::move(renderBuffer));
            renderBuffers[std::make_tuple(data.x, data.y, data.z)]->uploadChunkMesh(data);

            lock.lock(); // lock again to check the queue condition
        }
    }

    // for now, draw all the chunks in the world
    this->drawChunks();
}


void World::makeTestingMap(int size) {
    for (int x = -size; x <= size; x++) {
        for (int y = -size; y <= size; y++) {
            for (int z = -size; z <= size; z++) {
                std::unique_ptr<Chunk> chunk = std::make_unique<Chunk>(x, y, z);
                chunk->createRandomChunk();
                world.emplace(std::make_tuple(x, y, z), std::move(chunk));
            }
        }
    }

}


void World::drawChunks() const {
    for (const auto& [location, data] : renderBuffers) {
        shader->setVec3("chunkPos", (float)std::get<0>(location) * CHUNK_SIZE, (float)std::get<1>(location) * CHUNK_SIZE, (float)std::get<2>(location) * CHUNK_SIZE); // set the chunk position uniform to the world position of the chunk, this is used to calculate the world position of the vertices in the shader, so that they can be drawn in the correct position
        data->draw();
    }
}


void World::updateChunkGenerationQueue() {
    // lock the chunk generation queue mutex to provent data from reading at the same time
    std::lock_guard<std::mutex> lock(chunkGenerationQueueMutex);


    // get player chunk coordinates
    glm::ivec3 playerChunkCoords = player->getChunkCoords();


    // TODO: make it so that it generates the chunk in the corner later, for now keep as is
    // ----------
    // THIS FUNCTION MIGHT BE TERRIBLY SLOW, MAKE SURE THAT IT MIGHT NOT BE
    // add chunks around the player to the chunk generation queue, this is used to determine which chunks need to be generated based on the player's position
    for (int x = -RENDER_DISTANCE + playerChunkCoords.x; x <= RENDER_DISTANCE + playerChunkCoords.x; x++) {
        for (int y = -RENDER_DISTANCE + playerChunkCoords.y; y <= RENDER_DISTANCE + playerChunkCoords.y; y++) {
            for (int z = -RENDER_DISTANCE + playerChunkCoords.z; z <= RENDER_DISTANCE + playerChunkCoords.z; z++) {
                std::tuple<int, int, int> chunkCoords = std::make_tuple(x, y, z);
                if (world.find(chunkCoords) == world.end() 
                    && std::find(chunkGenerationQueue.begin(), chunkGenerationQueue.end(), chunkCoords) == chunkGenerationQueue.end()) {
                    
                    chunkGenerationQueue.push_front(chunkCoords);
                }
            }
        }
    }
}